name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags starting with "v" (e.g., v1.0.0)

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to create GitHub releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  # Use the version of Go your project requires

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest  # Or pin a specific version
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
